import { StyleSheet, Dimensions } from "react-native";
import type { ThemeColors } from "@shared/context/ThemeContext";

const { width, height: SCREEN_HEIGHT } = Dimensions.get("window");

const makeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    content: { padding: 10, paddingTop: 60, paddingBottom: 120 },
    header: { marginBottom: 25, alignItems: "center" },
    widgetsSectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 10,
    },
    widgetsSectionTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textSecondary,
    },
    widgetsEditToggle: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.accent,
    },
    pullHint: {
      position: "absolute",
      top: 8,
      left: 0,
      right: 0,
      alignItems: "center",
      zIndex: 10,
    },
    pullHintText: {
      backgroundColor: colors.accent,
      color: colors.surface,
      fontSize: 13,
      fontWeight: "600",
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 14,
      overflow: "hidden",
    },
    widgetLineMuted: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },
    title: {
      fontSize: 32,
      fontWeight: "bold",
      color: colors.textPrimary,
      marginBottom: 8,
    },
    subtitle: {
      fontSize: 16,
      color: colors.textSecondary,
      textAlign: "center",
    },

    weightEntryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 10,
    },
    weightEntryRowBorder: {
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    weightEntryDate: {
      fontSize: 14,
      fontWeight: "500",
      color: colors.textPrimary,
    },
    weightEntryTime: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
    weightEntryRight: { alignItems: "flex-end" },
    weightEntryValueRow: { flexDirection: "row", alignItems: "center", gap: 8 },
    weightEntryValue: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    weightEntryValueLatest: { color: colors.accent, fontSize: 18 },
    weightEntryLatestBadge: {
      fontSize: 11,
      color: colors.accent,
      fontWeight: "600",
      marginTop: 2,
    },
    deleteEntryBtn: { padding: 4, opacity: 0.55 },
    deleteEntryBtnText: { fontSize: 15 },
    loadMoreButton: {
      marginTop: 12,
      paddingVertical: 10,
      borderRadius: 8,
      backgroundColor: colors.accentLight,
      alignItems: "center",
    },
    loadMoreText: { fontSize: 14, color: colors.accent, fontWeight: "600" },

    trendContainer: { marginTop: 12, alignItems: "center" },
    trendBadge: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      gap: 6,
    },
    trendUp: { backgroundColor: colors.errorLight },
    trendDown: { backgroundColor: colors.successLight },
    trendStable: { backgroundColor: colors.separator },
    trendIcon: { fontSize: 16, fontWeight: "bold" },
    trendText: { fontSize: 14, fontWeight: "600", color: colors.textPrimary },
    trendPercent: { fontSize: 12, color: colors.textSecondary },
    trendSubtext: { fontSize: 11, color: colors.textMuted, marginTop: 4 },
    trendSelector: {
      flexDirection: "row",
      marginTop: 12,
      gap: 8,
      backgroundColor: colors.inputBackground,
      padding: 4,
      borderRadius: 10,
    },
    trendOption: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
    trendOptionActive: { backgroundColor: colors.accent },
    trendOptionText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    trendOptionTextActive: { color: colors.surface, fontWeight: "700" },

    section: { marginBottom: 25 },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 15,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.textPrimary,
    },

    statsCard: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 20,
      marginBottom: 15,
      alignItems: "center",
    },
    statsTitle: { fontSize: 14, color: colors.textSecondary, marginBottom: 8 },
    statsValue: { fontSize: 36, fontWeight: "bold", color: colors.accent },
    statsDate: { fontSize: 13, color: colors.textMuted, marginTop: 4 },

    buttonRow: { flexDirection: "row", gap: 10, marginBottom: 15 },
    primaryButton: {
      flex: 1,
      backgroundColor: colors.accent,
      padding: 14,
      borderRadius: 12,
      alignItems: "center",
    },
    primaryButtonText: {
      color: colors.surface,
      fontWeight: "700",
      fontSize: 15,
    },
    secondaryButton: {
      flex: 1,
      backgroundColor: colors.surface,
      padding: 14,
      borderRadius: 12,
      alignItems: "center",
      borderWidth: 2,
      borderColor: colors.accent,
    },
    secondaryButtonText: {
      color: colors.accent,
      fontWeight: "700",
      fontSize: 15,
    },
    goalButton: {
      backgroundColor: colors.accentLight,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 8,
    },
    goalButtonText: { color: colors.accent, fontWeight: "600", fontSize: 14 },

    statRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
    },
    statLabel: { fontSize: 15, color: colors.textSecondary },
    statValue: { fontSize: 15, fontWeight: "600", color: colors.textPrimary },

    macrosStatsCard: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 16,
      marginBottom: 15,
    },
    macrosStatsTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.textPrimary,
      marginBottom: 16,
    },
    macroRow: { marginBottom: 16 },
    macroLabelRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 4,
    },
    macroLabel: {
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: "500",
    },
    macroValue: { fontSize: 14, fontWeight: "700", color: colors.textPrimary },
    macroRange: { fontSize: 12, color: colors.textMuted, fontWeight: "normal" },
    macroProgressBar: {
      height: 10,
      backgroundColor: colors.separator,
      borderRadius: 5,
      overflow: "hidden",
    },
    macroProgressFill: { height: "100%", borderRadius: 5 },
    macroProgressText: { fontSize: 11, color: colors.textMuted, marginTop: 3 },
    macrosEntriesCount: {
      fontSize: 13,
      color: colors.textMuted,
      textAlign: "center",
      marginTop: 4,
    },

    bodyFatCard: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 20,
      alignItems: "center",
      marginBottom: 15,
    },
    bodyFatLabel: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 8,
    },
    bodyFatValue: {
      fontSize: 48,
      fontWeight: "bold",
      color: colors.accent,
      marginBottom: 4,
    },
    bodyFatDate: { fontSize: 13, color: colors.textMuted },
    bodyFatMethod: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 8,
      fontStyle: "italic",
    },
    bodyFatDeleteBtn: {
      marginTop: 16,
      backgroundColor: colors.errorLight,
      borderRadius: 8,
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    bodyFatDeleteBtnText: { fontSize: 13, color: "#dc2626", fontWeight: "600" },

    emptyState: {
      alignItems: "center",
      padding: 40,
      backgroundColor: colors.surface,
      borderRadius: 12,
      marginBottom: 15,
    },
    emptyText: { fontSize: 16, color: colors.textMuted },

    inputLabel: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 4,
      marginTop: 8,
    },
    inputLabelOptional: { fontSize: 12, color: "#aaa", fontWeight: "normal" },
    input: {
      color: colors.textSecondary,
      borderRadius: 12,
      padding: 14,
      fontSize: 16,
      marginBottom: 15,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
    },
    modalHint: {
      fontSize: 13,
      color: colors.textMuted,
      marginBottom: 15,
      textAlign: "center",
    },
    optionButton: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: colors.separator,
    },
    optionButtonActive: { backgroundColor: colors.accent },
    optionButtonText: { color: colors.textSecondary, fontWeight: "600" },
    optionButtonTextActive: { color: colors.surface, fontWeight: "700" },

    genderToggle: { flexDirection: "row", gap: 10, marginBottom: 15 },
    genderButton: {
      flex: 1,
      padding: 12,
      borderRadius: 8,
      backgroundColor: colors.separator,
      alignItems: "center",
    },
    genderButtonActive: { backgroundColor: colors.accent },
    genderButtonText: { color: colors.textSecondary, fontWeight: "600" },
    genderButtonTextActive: { color: colors.surface },

    unitToggleContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 15,
    },
    unitToggle: {
      flexDirection: "row",
      marginLeft: "auto",
      backgroundColor: colors.separator,
      borderRadius: 8,
      padding: 2,
    },
    unitButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
    unitButtonActive: { backgroundColor: colors.accent },
    unitButtonText: {
      color: colors.textSecondary,
      fontWeight: "600",
      fontSize: 12,
    },
    unitButtonTextActive: { color: colors.surface },

    optionalDivider: {
      flexDirection: "row",
      alignItems: "center",
      marginVertical: 12,
      gap: 8,
    },
    optionalDividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: colors.inputBorder,
    },
    optionalDividerText: {
      fontSize: 11,
      color: colors.textMuted,
      textAlign: "center",
      flexShrink: 1,
    },

    photoThumbWrap: { marginRight: 10, position: "relative" },
    photoThumb: { width: 110, height: 140, borderRadius: 10 },
    photoThumbLoading: {
      backgroundColor: colors.infoLight,
      alignItems: "center",
      justifyContent: "center",
    },
    photoThumbError: {
      backgroundColor: colors.errorLight,
      alignItems: "center",
      justifyContent: "center",
    },
    photoThumbDelete: {
      position: "absolute",
      top: 5,
      right: 5,
      backgroundColor: "rgba(0,0,0,0.5)",
      borderRadius: 10,
      width: 20,
      height: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    photoThumbDeleteText: {
      color: colors.surface,
      fontSize: 10,
      fontWeight: "700",
    },

    existingEntriesSection: {
      backgroundColor: colors.inputBackground,
      borderRadius: 12,
      padding: 14,
      marginTop: 16,
      marginBottom: 4,
    },
    existingEntriesTitle: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 10,
    },
    existingEntryRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.separator,
      gap: 10,
    },
    existingEntryTime: { fontSize: 12, color: colors.textMuted, minWidth: 44 },
    existingEntryValue: {
      flex: 1,
      fontSize: 16,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    existingEntryName: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    existingEntryMacros: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },
    existingEntryDelete: { fontSize: 17, opacity: 0.55 },
    cycleHistoryRow: {
      marginBottom: 12,
    },
    cycleToggleText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "700",
      alignSelf: "center",
    },
    cycleDetailsBox: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 14,
      marginTop: 8,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
    },
    cycleDetailsLine: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 6,
    },
    cycleDetailsNote: {
      fontSize: 13,
      color: colors.textPrimary,
      fontStyle: "italic",
    },

    logEntryBtn: {
      marginTop: 20,
      backgroundColor: colors.accent,
      padding: 16,
      borderRadius: 14,
      alignItems: "center",
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 4,
    },
    logEntryBtnText: { color: colors.surface, fontWeight: "700", fontSize: 16 },

    dayModalEmptyState: { alignItems: "center", paddingVertical: 32 },
    dayModalEmptyIcon: { fontSize: 40, marginBottom: 10, opacity: 0.3 },
    dayModalEmptyText: { fontSize: 15, color: colors.textMuted },

    dayModalHeader: {
      flexDirection: "row",
      alignItems: "center",
      padding: 20,
      paddingBottom: 16,
      gap: 12,
    },
    dayModalIconCircle: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.accentLight,
      alignItems: "center",
      justifyContent: "center",
    },
    dayModalIcon: { fontSize: 22 },
    dayModalHeaderText: { flex: 1 },
    dayModalTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.background,
    },
    dayModalSubtitle: { fontSize: 13, color: colors.textMuted, marginTop: 2 },
    dayModalDivider: {
      height: 1,
      backgroundColor: colors.separator,
      marginHorizontal: 20,
    },

    heightCard: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 16,
      marginBottom: 15,
      borderWidth: 2,
      borderColor: colors.infoLight,
    },
    heightDisplay: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    heightInfo: { flex: 1 },
    heightLabel: { fontSize: 13, color: colors.textSecondary, marginBottom: 4 },
    heightValue: {
      fontSize: 24,
      fontWeight: "bold",
      color: colors.accent,
      marginBottom: 4,
    },
    heightNote: { fontSize: 12, color: colors.textMuted, fontStyle: "italic" },
    heightEditButton: {
      backgroundColor: colors.accent,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 10,
    },
    heightEditButtonText: {
      color: colors.surface,
      fontWeight: "700",
      fontSize: 14,
    },
    heightSetButton: {
      flexDirection: "row",
      alignItems: "center",
      padding: 16,
      backgroundColor: colors.warningLight,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: colors.warning,
      borderStyle: "dashed",
    },
    heightSetIcon: { fontSize: 32, marginRight: 12 },
    heightSetTextContainer: { flex: 1 },
    heightSetTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: "#92400e",
      marginBottom: 4,
    },
    heightSetSubtitle: { fontSize: 13, color: "#92400e" },

    photoViewerOverlay: {
      flex: 1,
      backgroundColor: colors.shadow,
      justifyContent: "center",
      alignItems: "center",
    },
    photoViewerClose: {
      position: "absolute",
      top: 54,
      right: 20,
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: "rgba(255,255,255,0.18)",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 10,
    },
    photoViewerCloseText: {
      color: colors.surface,
      fontSize: 16,
      fontWeight: "700",
    },
    photoViewerImage: { width, height: SCREEN_HEIGHT * 0.8 },
    photoViewerInfo: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: "rgba(0,0,0,0.55)",
      paddingVertical: 20,
      paddingHorizontal: 24,
      paddingBottom: 36,
    },
    photoViewerTime: {
      color: colors.surface,
      fontSize: 14,
      fontWeight: "500",
      textAlign: "center",
    },
    photoViewerNote: {
      color: "rgba(255,255,255,0.75)",
      fontSize: 13,
      textAlign: "center",
      marginTop: 4,
      fontStyle: "italic",
    },

    trackerHeroCard: {
      borderRadius: 16,
      borderWidth: 1,
      padding: 18,
    },
    trackerHeroTop: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    trackerHeroBadge: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    trackerHeroBadgeIcon: { fontSize: 18 },
    trackerHeroLabel: {
      fontSize: 12,
      fontWeight: "600",
      letterSpacing: 0.4,
      textTransform: "uppercase",
    },
    trackerHeroValue: {
      fontSize: 28,
      fontWeight: "700",
      marginTop: 10,
    },
    trackerHeroDate: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 2,
    },
    trackerHeroButton: {
      marginTop: 14,
      borderRadius: 10,
      paddingVertical: 11,
      alignItems: "center",
    },
    trackerHeroButtonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 14,
    },
    trackerEmptyCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      borderStyle: "dashed",
      padding: 24,
      alignItems: "center",
    },
    trackerEmptyIcon: { fontSize: 24, marginBottom: 8 },
    trackerEmptyText: {
      fontSize: 13,
      color: colors.textMuted,
      textAlign: "center",
      marginBottom: 12,
    },
    trackerHistoryList: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
      overflow: "hidden",
    },
    trackerHistoryRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 12,
      paddingHorizontal: 14,
      backgroundColor: colors.surface,
    },
    trackerHistoryRowBorder: {
      borderBottomWidth: 1,
      borderBottomColor: colors.surfaceBorder,
    },
    trackerHistoryLeft: { flexDirection: "row", alignItems: "center", flex: 1 },
    trackerHistoryDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginRight: 10,
    },
    trackerHistoryDate: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textPrimary,
    },
    trackerHistoryTime: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 2,
    },
    trackerHistoryRight: { flexDirection: "row", alignItems: "center" },
    trackerHistoryValue: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textPrimary,
      marginRight: 10,
    },
    trackerDeleteBtn: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
    },
    trackerDeleteBtnText: { fontSize: 13 },
    dangerButton: {
      marginTop: 16,
      paddingVertical: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: "#fca5a5",
      backgroundColor: "#fee2e2",
      alignItems: "center",
      justifyContent: "center",
    },
    dangerButtonText: {
      color: "#7f1d1d",
      fontSize: 14,
      fontWeight: "600",
    },
  });

export default makeStyles;
